[ALPS08309937] Add missing header files
For example:

error: call to undeclared function pinctrl_gpio_direction_input; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]

MTK-Commit-Id: 6db652878e13eb77642123b37f7fe037af051bd5

CR-Id: ALPS08309937
Feature: Kernel SI Operation
Signed-off-by: Lili Lin <lili.lin@mediatek.com>
Change-Id: Idb0a14d43df9154609ed2c70c2ab1f9aa05c4028